// This code was generated by a tool on Fri, 19 Feb 2021 19:47:03 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Alexa.Cooking.PresetController'.

#ifndef __ACK_GENERATED_ALEXA_COOKING_PRESET_CONTROLLER_H__
#define __ACK_GENERATED_ALEXA_COOKING_PRESET_CONTROLLER_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_alexa_cooking_preset_controller_property_name
{
    ack_alexa_cooking_preset_controller_property_name_preset_name = 1,
    ack_alexa_cooking_preset_controller_property_name_requested_food_doneness = 2
}
ack_alexa_cooking_preset_controller_property_name;

typedef enum _ack_alexa_cooking_preset_controller_directive_name
{
    ack_alexa_cooking_preset_controller_directive_name_cook_by_preset = 1
}
ack_alexa_cooking_preset_controller_directive_name;

typedef enum _ack_alexa_cooking_preset_controller_cook_by_preset_payload_object_member
{
    ack_alexa_cooking_preset_controller_cook_by_preset_payload_object_member_preset_name = 1,
    ack_alexa_cooking_preset_controller_cook_by_preset_payload_object_member_cooking_mode = 2,
    ack_alexa_cooking_preset_controller_cook_by_preset_payload_object_member_food_item = 3,
    ack_alexa_cooking_preset_controller_cook_by_preset_payload_object_member_requested_food_doneness = 4
}
ack_alexa_cooking_preset_controller_cook_by_preset_payload_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ALEXA_COOKING_PRESET_CONTROLLER_H__
