// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'PowerLevel'.

#ifndef __ACK_GENERATED_POWER_LEVEL_H__
#define __ACK_GENERATED_POWER_LEVEL_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_power_level_object_member
{
    ack_power_level_object_member_type = 1,
    ack_power_level_object_member_value = 2
}
ack_power_level_object_member;

typedef enum _ack_power_level_object_type
{
    ack_power_level_object_type_enumerated_power_level = 1,
    ack_power_level_object_type_integral_power_level = 2
}
ack_power_level_object_type;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_POWER_LEVEL_H__
