// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'DeviceState'.

#ifndef __ACK_GENERATED_DEVICE_STATE_H__
#define __ACK_GENERATED_DEVICE_STATE_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_device_state_object_member
{
    ack_device_state_object_member_value = 1
}
ack_device_state_object_member;

typedef enum _ack_device_state
{
    ack_device_state_preheated = 1
}
ack_device_state;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_DEVICE_STATE_H__
