// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'IntegralPowerLevel'.

#ifndef __ACK_GENERATED_INTEGRAL_POWER_LEVEL_H__
#define __ACK_GENERATED_INTEGRAL_POWER_LEVEL_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_integral_power_level_object_member
{
    ack_integral_power_level_object_member_value = 1
}
ack_integral_power_level_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_INTEGRAL_POWER_LEVEL_H__
