// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Alexa.TimeHoldController'.

#ifndef __ACK_GENERATED_ALEXA_TIME_HOLD_CONTROLLER_H__
#define __ACK_GENERATED_ALEXA_TIME_HOLD_CONTROLLER_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_alexa_time_hold_controller_property_name
{
    ack_alexa_time_hold_controller_property_name_hold_start_time = 1,
    ack_alexa_time_hold_controller_property_name_hold_end_time = 2
}
ack_alexa_time_hold_controller_property_name;

typedef enum _ack_alexa_time_hold_controller_directive_name
{
    ack_alexa_time_hold_controller_directive_name_hold = 1,
    ack_alexa_time_hold_controller_directive_name_resume = 2
}
ack_alexa_time_hold_controller_directive_name;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ALEXA_TIME_HOLD_CONTROLLER_H__
