// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'InventoryLevel'.

#ifndef __ACK_GENERATED_INVENTORY_LEVEL_H__
#define __ACK_GENERATED_INVENTORY_LEVEL_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_inventory_level_object_member
{
    ack_inventory_level_object_member_type = 1,
    ack_inventory_level_object_member_value = 2
}
ack_inventory_level_object_member;

typedef enum _ack_inventory_level_object_type
{
    ack_inventory_level_object_type_percentage = 1,
    ack_inventory_level_object_type_volume = 2,
    ack_inventory_level_object_type_weight = 3,
    ack_inventory_level_object_type_count = 4
}
ack_inventory_level_object_type;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_INVENTORY_LEVEL_H__
