// This code was generated by a tool on Wed, 3 Jun 2020 22:07:09 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Alexa.ColorController'.

#ifndef __ACK_GENERATED_ALEXA_COLOR_CONTROLLER_H__
#define __ACK_GENERATED_ALEXA_COLOR_CONTROLLER_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_alexa_color_controller_property_name
{
    ack_alexa_color_controller_property_name_color = 1
}
ack_alexa_color_controller_property_name;

typedef enum _ack_alexa_color_controller_directive_name
{
    ack_alexa_color_controller_directive_name_set_color = 1
}
ack_alexa_color_controller_directive_name;

typedef enum _ack_alexa_color_controller_set_color_directive_payload_object_member
{
    ack_alexa_color_controller_set_color_directive_payload_object_member_color = 1
}
ack_alexa_color_controller_set_color_directive_payload_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ALEXA_COLOR_CONTROLLER_H__
