// This code was generated by a tool on Tue, 14 Sep 2021 18:26:21 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Alexa.Cooking'.

#ifndef __ACK_GENERATED_ALEXA_COOKING_H__
#define __ACK_GENERATED_ALEXA_COOKING_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_alexa_cooking_property_name
{
    ack_alexa_cooking_property_name_cooking_mode = 1,
    ack_alexa_cooking_property_name_food_item = 2,
    ack_alexa_cooking_property_name_cooking_time_interval = 3,
    ack_alexa_cooking_property_name_cooking_status = 4
}
ack_alexa_cooking_property_name;

typedef enum _ack_alexa_cooking_set_cooking_mode_payload_object_member
{
    ack_alexa_cooking_set_cooking_mode_payload_object_member_cooking_mode = 1,
    ack_alexa_cooking_set_cooking_mode_payload_object_member_food_item = 2
}
ack_alexa_cooking_set_cooking_mode_payload_object_member;

typedef enum _ack_alexa_cooking_directive_name
{
    ack_alexa_cooking_directive_name_set_cooking_mode = 1
}
ack_alexa_cooking_directive_name;

typedef enum _ack_alexa_cooking_event_name
{
    ack_alexa_cooking_event_name_error_response = 1,
    ack_alexa_cooking_event_name_cooking_session_completed = 2,
    ack_alexa_cooking_event_name_cooking_session_interaction = 3,
    ack_alexa_cooking_event_name_device_state_change = 4
}
ack_alexa_cooking_event_name;

typedef enum _ack_alexa_cooking_device_state_change_payload_object_member
{
    ack_alexa_cooking_device_state_change_payload_object_member_device_state = 1
}
ack_alexa_cooking_device_state_change_payload_object_member;

typedef enum _ack_alexa_cooking_error_type
{
    ack_alexa_cooking_error_type_door_open = 1,
    ack_alexa_cooking_error_type_door_closed_too_long = 2,
    ack_alexa_cooking_error_type_cook_duration_too_long = 3,
    ack_alexa_cooking_error_type_remote_start_not_supported = 4,
    ack_alexa_cooking_error_type_remote_start_disabled = 5,
    ack_alexa_cooking_error_type_preheat_required = 6,
    ack_alexa_cooking_error_type_probe_required = 7,
    ack_alexa_cooking_error_type_remove_probe = 8,
    ack_alexa_cooking_error_type_child_lock = 9
}
ack_alexa_cooking_error_type;

typedef enum _ack_alexa_cooking_cooking_session_completed_payload_object_member
{
    ack_alexa_cooking_cooking_session_completed_payload_object_member_time_of_completion = 1
}
ack_alexa_cooking_cooking_session_completed_payload_object_member;

typedef enum _ack_alexa_cooking_cooking_session_interaction_payload_object_member
{
    ack_alexa_cooking_cooking_session_interaction_payload_object_member_required_interaction = 1
}
ack_alexa_cooking_cooking_session_interaction_payload_object_member;

typedef enum _ack_alexa_cooking_error_response_payload_object_member
{
    ack_alexa_cooking_error_response_payload_object_member_type = 1,
    ack_alexa_cooking_error_response_payload_object_member_message = 2,
    ack_alexa_cooking_error_response_payload_object_member_cook_duration_too_long_max_cook_time = 3
}
ack_alexa_cooking_error_response_payload_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ALEXA_COOKING_H__
