// This code was generated by a tool on Tue, 16 Jun 2020 01:08:05 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Alexa.TemperatureSensor'.

#ifndef __ACK_GENERATED_ALEXA_TEMPERATURE_SENSOR_H__
#define __ACK_GENERATED_ALEXA_TEMPERATURE_SENSOR_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_alexa_temperature_sensor_property_name
{
    ack_alexa_temperature_sensor_property_name_temperature = 1
}
ack_alexa_temperature_sensor_property_name;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ALEXA_TEMPERATURE_SENSOR_H__
