// This code was generated by a tool on Tue, 14 Sep 2021 18:26:21 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'CookingStatus'.

#ifndef __ACK_GENERATED_COOKING_STATUS_H__
#define __ACK_GENERATED_COOKING_STATUS_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_cooking_status
{
    ack_cooking_status_cooking = 1,
    ack_cooking_status_preheating = 2,
    ack_cooking_status_preheating_completed = 3,
    ack_cooking_status_food_target_temperature_reached = 4,
    ack_cooking_status_cooking_completed = 5,
    ack_cooking_status_not_in_use = 6,
    ack_cooking_status_ready = 7
}
ack_cooking_status;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_COOKING_STATUS_H__
