// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Volume'.

#ifndef __ACK_GENERATED_VOLUME_H__
#define __ACK_GENERATED_VOLUME_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_volume_unit
{
    ack_volume_unit_liter = 1,
    ack_volume_unit_milliliter = 2,
    ack_volume_unit_teaspoon = 3,
    ack_volume_unit_uk_teaspoon = 4,
    ack_volume_unit_au_teaspoon = 5,
    ack_volume_unit_cubic_centimeter = 6,
    ack_volume_unit_cubic_meter = 7,
    ack_volume_unit_uk_gallon = 8,
    ack_volume_unit_uk_quart = 9,
    ack_volume_unit_uk_pint = 10,
    ack_volume_unit_uk_cup = 11,
    ack_volume_unit_uk_gill = 12,
    ack_volume_unit_uk_ounce = 13,
    ack_volume_unit_uk_dram = 14,
    ack_volume_unit_us_fluid_gallon = 15,
    ack_volume_unit_us_fluid_quart = 16,
    ack_volume_unit_us_fluid_pint = 17,
    ack_volume_unit_us_fluid_cup = 18,
    ack_volume_unit_us_fluid_ounce = 19,
    ack_volume_unit_us_tablespoon = 20,
    ack_volume_unit_us_teaspoon = 21,
    ack_volume_unit_us_dram = 22,
    ack_volume_unit_us_dry_gallon = 23,
    ack_volume_unit_us_dry_quart = 24,
    ack_volume_unit_us_dry_pint = 25,
    ack_volume_unit_us_dry_cup = 26,
    ack_volume_unit_us_dry_ounce = 27,
    ack_volume_unit_cubic_inch = 28,
    ack_volume_unit_cubic_foot = 29,
    ack_volume_unit_cubic_yard = 30,
    ack_volume_unit_metric_cup = 31,
    ack_volume_unit_metric_teaspoon = 32,
    ack_volume_unit_uk_fluid_dram = 33,
    ack_volume_unit_uk_fluid_ounce = 34,
    ack_volume_unit_us_gill = 35
}
ack_volume_unit;

typedef enum _ack_volume_object_member
{
    ack_volume_object_member_value = 1,
    ack_volume_object_member_unit = 2
}
ack_volume_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_VOLUME_H__
