// This code was generated by a tool on Wed, 3 Jun 2020 22:07:09 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Alexa.ColorTemperatureController'.

#ifndef __ACK_GENERATED_ALEXA_COLOR_TEMPERATURE_CONTROLLER_H__
#define __ACK_GENERATED_ALEXA_COLOR_TEMPERATURE_CONTROLLER_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_alexa_color_temperature_controller_property_name
{
    ack_alexa_color_temperature_controller_property_name_color_temperature_in_kelvin = 1
}
ack_alexa_color_temperature_controller_property_name;

typedef enum _ack_alexa_color_temperature_controller_directive_name
{
    ack_alexa_color_temperature_controller_directive_name_set_color_temperature = 1,
    ack_alexa_color_temperature_controller_directive_name_increase_color_temperature = 2,
    ack_alexa_color_temperature_controller_directive_name_decrease_color_temperature = 3
}
ack_alexa_color_temperature_controller_directive_name;

typedef enum _ack_alexa_color_temperature_controller_set_color_temperature_directive_payload_object_member
{
    ack_alexa_color_temperature_controller_set_color_temperature_directive_payload_object_member_color_temperature_in_kelvin = 1
}
ack_alexa_color_temperature_controller_set_color_temperature_directive_payload_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ALEXA_COLOR_TEMPERATURE_CONTROLLER_H__
