// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Alexa.PercentageController'.

#ifndef __ACK_GENERATED_ALEXA_PERCENTAGE_CONTROLLER_H__
#define __ACK_GENERATED_ALEXA_PERCENTAGE_CONTROLLER_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_alexa_percentage_controller_property_name
{
    ack_alexa_percentage_controller_property_name_percentage = 1
}
ack_alexa_percentage_controller_property_name;

typedef enum _ack_alexa_percentage_controller_directive_name
{
    ack_alexa_percentage_controller_directive_name_set_percentage = 1,
    ack_alexa_percentage_controller_directive_name_adjust_percentage = 2
}
ack_alexa_percentage_controller_directive_name;

typedef enum _ack_alexa_percentage_controller_set_percentage_directive_payload_object_member
{
    ack_alexa_percentage_controller_set_percentage_directive_payload_object_member_percentage = 1
}
ack_alexa_percentage_controller_set_percentage_directive_payload_object_member;

typedef enum _ack_alexa_percentage_controller_adjust_percentage_directive_payload_object_member
{
    ack_alexa_percentage_controller_adjust_percentage_directive_payload_object_member_percentage_delta = 1
}
ack_alexa_percentage_controller_adjust_percentage_directive_payload_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ALEXA_PERCENTAGE_CONTROLLER_H__
