// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Weight'.

#ifndef __ACK_GENERATED_WEIGHT_H__
#define __ACK_GENERATED_WEIGHT_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_weight_object_member
{
    ack_weight_object_member_value = 1,
    ack_weight_object_member_unit = 2
}
ack_weight_object_member;

typedef enum _ack_weight_unit
{
    ack_weight_unit_kilogram = 1,
    ack_weight_unit_gram = 2,
    ack_weight_unit_milligram = 3,
    ack_weight_unit_microgram = 4,
    ack_weight_unit_metric_pound = 5,
    ack_weight_unit_pound = 6,
    ack_weight_unit_ounce = 7,
    ack_weight_unit_dram = 8
}
ack_weight_unit;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_WEIGHT_H__
