// This code was generated by a tool on Wed, 3 Jun 2020 22:07:09 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Alexa.Cooking.FoodTemperatureController'.

#ifndef __ACK_GENERATED_ALEXA_COOKING_FOOD_TEMPERATURE_CONTROLLER_H__
#define __ACK_GENERATED_ALEXA_COOKING_FOOD_TEMPERATURE_CONTROLLER_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_alexa_cooking_food_temperature_controller_property_name
{
    ack_alexa_cooking_food_temperature_controller_property_name_target_food_temperature = 1
}
ack_alexa_cooking_food_temperature_controller_property_name;

typedef enum _ack_alexa_cooking_food_temperature_controller_directive_name
{
    ack_alexa_cooking_food_temperature_controller_directive_name_cook_by_food_temperature = 1
}
ack_alexa_cooking_food_temperature_controller_directive_name;

typedef enum _ack_alexa_cooking_food_temperature_controller_cook_by_food_temperature_payload_object_member
{
    ack_alexa_cooking_food_temperature_controller_cook_by_food_temperature_payload_object_member_target_food_temperature = 1,
    ack_alexa_cooking_food_temperature_controller_cook_by_food_temperature_payload_object_member_cooking_mode = 2,
    ack_alexa_cooking_food_temperature_controller_cook_by_food_temperature_payload_object_member_food_item = 3
}
ack_alexa_cooking_food_temperature_controller_cook_by_food_temperature_payload_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ALEXA_COOKING_FOOD_TEMPERATURE_CONTROLLER_H__
