// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Temperature'.

#ifndef __ACK_GENERATED_TEMPERATURE_H__
#define __ACK_GENERATED_TEMPERATURE_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_temperature_object_member
{
    ack_temperature_object_member_value = 1,
    ack_temperature_object_member_scale = 2
}
ack_temperature_object_member;

typedef enum _ack_temperature_scale
{
    ack_temperature_scale_celsius = 1,
    ack_temperature_scale_fahrenheit = 2,
    ack_temperature_scale_kelvin = 3,
    ack_temperature_scale_delisle = 4,
    ack_temperature_scale_newton = 5,
    ack_temperature_scale_rankine = 6,
    ack_temperature_scale_reaumur = 7,
    ack_temperature_scale_romer = 8
}
ack_temperature_scale;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_TEMPERATURE_H__
