// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Length'.

#ifndef __ACK_GENERATED_LENGTH_H__
#define __ACK_GENERATED_LENGTH_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_length_object_member
{
    ack_length_object_member_value = 1,
    ack_length_object_member_unit = 2
}
ack_length_object_member;

typedef enum _ack_length_unit
{
    ack_length_unit_meter = 1,
    ack_length_unit_kilometer = 2,
    ack_length_unit_centimeter = 3,
    ack_length_unit_millimeter = 4,
    ack_length_unit_inch = 5,
    ack_length_unit_span = 6,
    ack_length_unit_foot = 7,
    ack_length_unit_yard = 8,
    ack_length_unit_mile = 9
}
ack_length_unit;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_LENGTH_H__
