// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Count'.

#ifndef __ACK_GENERATED_COUNT_H__
#define __ACK_GENERATED_COUNT_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_count_unit
{
    ack_count_unit_extra_extra_large = 1,
    ack_count_unit_jumbo = 2,
    ack_count_unit_extra_large = 3,
    ack_count_unit_large = 4,
    ack_count_unit_medium = 5,
    ack_count_unit_small = 6,
    ack_count_unit_extra_small = 7,
    ack_count_unit_extra_extra_small = 8,
    ack_count_unit_size_a = 9,
    ack_count_unit_size_b = 10
}
ack_count_unit;

typedef enum _ack_count_object_member
{
    ack_count_object_member_value = 1,
    ack_count_object_member_unit = 2
}
ack_count_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_COUNT_H__
