// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Alexa.Cooking.TemperatureSensor'.

#ifndef __ACK_GENERATED_ALEXA_COOKING_TEMPERATURE_SENSOR_H__
#define __ACK_GENERATED_ALEXA_COOKING_TEMPERATURE_SENSOR_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_alexa_cooking_temperature_sensor_property_name
{
    ack_alexa_cooking_temperature_sensor_property_name_cooking_temperature = 1
}
ack_alexa_cooking_temperature_sensor_property_name;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ALEXA_COOKING_TEMPERATURE_SENSOR_H__
