// This code was generated by a tool on Fri, 19 Feb 2021 19:47:03 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'FoodDoneness'.

#ifndef __ACK_GENERATED_FOOD_DONENESS_H__
#define __ACK_GENERATED_FOOD_DONENESS_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_food_doneness
{
    ack_food_doneness_al_dente = 1,
    ack_food_doneness_creamy = 2,
    ack_food_doneness_crispy = 3,
    ack_food_doneness_dry = 4,
    ack_food_doneness_firm = 5,
    ack_food_doneness_flaky = 6,
    ack_food_doneness_hard = 7,
    ack_food_doneness_juicy = 8,
    ack_food_doneness_medium = 9,
    ack_food_doneness_medium_rare = 10,
    ack_food_doneness_medium_well = 11,
    ack_food_doneness_moist = 12,
    ack_food_doneness_opaque = 13,
    ack_food_doneness_overcooked = 14,
    ack_food_doneness_rare = 15,
    ack_food_doneness_runny = 16,
    ack_food_doneness_smooth = 17,
    ack_food_doneness_soft = 18,
    ack_food_doneness_springy = 19,
    ack_food_doneness_succulent = 20,
    ack_food_doneness_tender = 21,
    ack_food_doneness_undercooked = 22,
    ack_food_doneness_velvety = 23,
    ack_food_doneness_well_done = 24
}
ack_food_doneness;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_FOOD_DONENESS_H__
