// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'TimeInterval'.

#ifndef __ACK_GENERATED_TIME_INTERVAL_H__
#define __ACK_GENERATED_TIME_INTERVAL_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_time_interval_object_member
{
    ack_time_interval_object_member_start = 1,
    ack_time_interval_object_member_end = 2,
    ack_time_interval_object_member_duration = 3
}
ack_time_interval_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_TIME_INTERVAL_H__
