// This code was generated by a tool on Mon, 19 Jul 2021 20:48:17 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'ack'.

#ifndef __ACK_GENERATED_ACK_H__
#define __ACK_GENERATED_ACK_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_directive_header_object_member
{
    ack_directive_header_object_member_namespace = 1,
    ack_directive_header_object_member_name = 2
}
ack_directive_header_object_member;

typedef enum _ack_directive_message_member
{
    ack_directive_message_member_directive = 1
}
ack_directive_message_member;

typedef enum _ack_namespace
{
    ack_namespace_alexa = 0,
    ack_namespace_alexa_color_controller = 1,
    ack_namespace_alexa_power_controller = 2,
    ack_namespace_alexa_percentage_controller = 3,
    ack_namespace_alexa_brightness_controller = 4,
    ack_namespace_alexa_color_temperature_controller = 5,
    ack_namespace_alexa_thermostat_controller = 6,
    ack_namespace_alexa_mode_controller = 7,
    ack_namespace_alexa_time_hold_controller = 8,
    ack_namespace_alexa_endpoint_health = 9,
    ack_namespace_alexa_cooking = 10,
    ack_namespace_alexa_cooking_food_temperature_controller = 11,
    ack_namespace_alexa_cooking_food_temperature_sensor = 12,
    ack_namespace_alexa_cooking_preset_controller = 13,
    ack_namespace_alexa_cooking_temperature_controller = 14,
    ack_namespace_alexa_cooking_temperature_sensor = 15,
    ack_namespace_alexa_cooking_time_controller = 16,
    ack_namespace_alexa_range_controller = 17,
    ack_namespace_alexa_toggle_controller = 18,
    ack_namespace_alexa_temperature_sensor = 19,
    ack_namespace_alexa_inventory_level_sensor = 20,
    ack_namespace_alexa_inventory_level_usage_sensor = 21,
    ack_namespace_alexa_inventory_usage_sensor = 22,
    ack_namespace_alexa_device_usage_meter = 25,
    ack_namespace_alexa_device_usage_estimation = 26,
    ack_namespace_dummy_capability = 500
}
ack_namespace;

typedef enum _ack_endpoint_object_member
{
    ack_endpoint_object_member_endpoint_id = 1
}
ack_endpoint_object_member;

typedef enum _ack_event_message_member
{
    ack_event_message_member_event = 1,
    ack_event_message_member_context = 2
}
ack_event_message_member;

typedef enum _ack_property_object_member
{
    ack_property_object_member_namespace = 1,
    ack_property_object_member_name = 2,
    ack_property_object_member_value = 3,
    ack_property_object_member_time_of_sample = 4,
    ack_property_object_member_uncertainty_in_milliseconds = 5,
    ack_property_object_member_instance = 6
}
ack_property_object_member;

typedef enum _ack_context_object_member
{
    ack_context_object_member_properties = 1
}
ack_context_object_member;

typedef enum _ack_event_header_object_member
{
    ack_event_header_object_member_namespace = 1,
    ack_event_header_object_member_name = 2
}
ack_event_header_object_member;

typedef enum _ack_directive_object_member
{
    ack_directive_object_member_header = 1,
    ack_directive_object_member_payload = 2,
    ack_directive_object_member_endpoint = 3
}
ack_directive_object_member;

typedef enum _ack_event_object_member
{
    ack_event_object_member_header = 1,
    ack_event_object_member_payload = 2,
    ack_event_object_member_endpoint = 3
}
ack_event_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ACK_H__
