// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'ThermostatMode'.

#ifndef __ACK_GENERATED_THERMOSTAT_MODE_H__
#define __ACK_GENERATED_THERMOSTAT_MODE_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_thermostat_mode
{
    ack_thermostat_mode_auto = 1,
    ack_thermostat_mode_cool = 2,
    ack_thermostat_mode_heat = 3,
    ack_thermostat_mode_eco = 4,
    ack_thermostat_mode_off = 5
}
ack_thermostat_mode;

typedef enum _ack_thermostat_mode_object_member
{
    ack_thermostat_mode_object_member_value = 1
}
ack_thermostat_mode_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_THERMOSTAT_MODE_H__
