// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Color'.

#ifndef __ACK_GENERATED_COLOR_H__
#define __ACK_GENERATED_COLOR_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_color_object_member
{
    ack_color_object_member_hue = 1,
    ack_color_object_member_saturation = 2,
    ack_color_object_member_brightness = 3
}
ack_color_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_COLOR_H__
