// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Alexa.EndpointHealth'.

#ifndef __ACK_GENERATED_ALEXA_ENDPOINT_HEALTH_H__
#define __ACK_GENERATED_ALEXA_ENDPOINT_HEALTH_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_alexa_endpoint_health_property_name
{
    ack_alexa_endpoint_health_property_name_connectivity = 1
}
ack_alexa_endpoint_health_property_name;

typedef enum _ack_alexa_endpoint_health_connectivity_property_value_object_member
{
    ack_alexa_endpoint_health_connectivity_property_value_object_member_value = 1
}
ack_alexa_endpoint_health_connectivity_property_value_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ALEXA_ENDPOINT_HEALTH_H__
