// This code was generated by a tool on Mon, 6 Jul 2020 19:25:29 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'FoodItem'.

#ifndef __ACK_GENERATED_FOOD_ITEM_H__
#define __ACK_GENERATED_FOOD_ITEM_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_food_item_food_category
{
    ack_food_item_food_category_beef = 1,
    ack_food_item_food_category_beverage = 2,
    ack_food_item_food_category_chicken = 3,
    ack_food_item_food_category_fish = 4,
    ack_food_item_food_category_meat = 5,
    ack_food_item_food_category_pasta = 6,
    ack_food_item_food_category_pizza = 7,
    ack_food_item_food_category_popcorn = 8,
    ack_food_item_food_category_pork = 9,
    ack_food_item_food_category_potato = 10,
    ack_food_item_food_category_shrimp = 11,
    ack_food_item_food_category_soup = 12,
    ack_food_item_food_category_turkey = 13,
    ack_food_item_food_category_vegetable = 14,
    ack_food_item_food_category_water = 15,
    ack_food_item_food_category_unknown = 16,
    ack_food_item_food_category_steak = 17
}
ack_food_item_food_category;

typedef enum _ack_food_item_food_state
{
    ack_food_item_food_state_fresh = 1,
    ack_food_item_food_state_frozen = 2
}
ack_food_item_food_state;

typedef enum _ack_food_item_object_member
{
    ack_food_item_object_member_food_name = 1,
    ack_food_item_object_member_food_category = 2,
    ack_food_item_object_member_food_quantity = 3,
    ack_food_item_object_member_food_state = 4,
    ack_food_item_object_member_food_thickness = 5
}
ack_food_item_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_FOOD_ITEM_H__
