// This code was generated by a tool on Tue, 14 Sep 2021 18:26:21 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'CookingMode'.

#ifndef __ACK_GENERATED_COOKING_MODE_H__
#define __ACK_GENERATED_COOKING_MODE_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_cooking_mode_object_member
{
    ack_cooking_mode_object_member_value = 1,
    ack_cooking_mode_object_member_custom_name = 2
}
ack_cooking_mode_object_member;

typedef enum _ack_cooking_mode
{
    ack_cooking_mode_timecook = 1,
    ack_cooking_mode_preset = 2,
    ack_cooking_mode_defrost = 3,
    ack_cooking_mode_reheat = 4,
    ack_cooking_mode_bake = 5,
    ack_cooking_mode_broil = 6,
    ack_cooking_mode_roast = 7,
    ack_cooking_mode_toast = 8,
    ack_cooking_mode_steam = 9,
    ack_cooking_mode_slow_cook = 10,
    ack_cooking_mode_sous_vide = 11,
    ack_cooking_mode_pressure = 12,
    ack_cooking_mode_saute = 13,
    ack_cooking_mode_sear = 14,
    ack_cooking_mode_brew = 15,
    ack_cooking_mode_smoke = 16,
    ack_cooking_mode_warm = 17,
    ack_cooking_mode_custom = 18,
    ack_cooking_mode_off = 19,
    ack_cooking_mode_air_fry = 20,
    ack_cooking_mode_boil = 21,
    ack_cooking_mode_blanch = 22,
    ack_cooking_mode_brown = 23,
    ack_cooking_mode_can = 24,
    ack_cooking_mode_convection_bake = 25,
    ack_cooking_mode_convection_broil = 26,
    ack_cooking_mode_convection_roast = 27,
    ack_cooking_mode_convection_steam = 28,
    ack_cooking_mode_cure = 29,
    ack_cooking_mode_dehydrate = 30,
    ack_cooking_mode_ferment = 31,
    ack_cooking_mode_fry = 32,
    ack_cooking_mode_grill = 33,
    ack_cooking_mode_incubate = 34,
    ack_cooking_mode_melt = 35,
    ack_cooking_mode_proof = 36,
    ack_cooking_mode_simmer = 37,
    ack_cooking_mode_soften = 38,
    ack_cooking_mode_sterilize = 39,
    ack_cooking_mode_stew = 40,
    ack_cooking_mode_stir_fry = 41,
    ack_cooking_mode_microwave = 42
}
ack_cooking_mode;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_COOKING_MODE_H__
