// This code was generated by a tool on Fri, 16 Apr 2021 23:28:24 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'InventoryLevelUsage'.

#ifndef __ACK_GENERATED_INVENTORY_LEVEL_USAGE_H__
#define __ACK_GENERATED_INVENTORY_LEVEL_USAGE_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_inventory_level_usage_object_type
{
    ack_inventory_level_usage_object_type_duration = 1
}
ack_inventory_level_usage_object_type;

typedef enum _ack_inventory_level_usage_object_member
{
    ack_inventory_level_usage_object_member_type = 1,
    ack_inventory_level_usage_object_member_value = 2
}
ack_inventory_level_usage_object_member;

typedef enum _ack_inventory_level_usage_time_duration_object_member
{
    ack_inventory_level_usage_time_duration_object_member_value = 1
}
ack_inventory_level_usage_time_duration_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_INVENTORY_LEVEL_USAGE_H__
