// This code was generated by a tool on Thu, 19 Nov 2020 16:15:38 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Alexa.ThermostatController'.

#ifndef __ACK_GENERATED_ALEXA_THERMOSTAT_CONTROLLER_H__
#define __ACK_GENERATED_ALEXA_THERMOSTAT_CONTROLLER_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_alexa_thermostat_controller_property_name
{
    ack_alexa_thermostat_controller_property_name_thermostat_mode = 1,
    ack_alexa_thermostat_controller_property_name_target_setpoint = 2,
    ack_alexa_thermostat_controller_property_name_lower_setpoint = 3,
    ack_alexa_thermostat_controller_property_name_upper_setpoint = 4,
    ack_alexa_thermostat_controller_property_name_adaptive_recovery_status = 5
}
ack_alexa_thermostat_controller_property_name;

typedef enum _ack_alexa_thermostat_controller_directive_name
{
    ack_alexa_thermostat_controller_directive_name_set_target_temperature = 1,
    ack_alexa_thermostat_controller_directive_name_adjust_target_temperature = 2,
    ack_alexa_thermostat_controller_directive_name_set_thermostat_mode = 3,
    ack_alexa_thermostat_controller_directive_name_resume_schedule = 4
}
ack_alexa_thermostat_controller_directive_name;

typedef enum _ack_alexa_thermostat_controller_adjust_target_temperature_payload_object_member
{
    ack_alexa_thermostat_controller_adjust_target_temperature_payload_object_member_target_setpoint_delta = 1
}
ack_alexa_thermostat_controller_adjust_target_temperature_payload_object_member;

typedef enum _ack_alexa_thermostat_controller_set_mode_payload_object_member
{
    ack_alexa_thermostat_controller_set_mode_payload_object_member_thermostat_mode = 1
}
ack_alexa_thermostat_controller_set_mode_payload_object_member;

typedef enum _ack_alexa_thermostat_controller_set_target_temperature_payload_object_member
{
    ack_alexa_thermostat_controller_set_target_temperature_payload_object_member_target_setpoint = 1,
    ack_alexa_thermostat_controller_set_target_temperature_payload_object_member_lower_setpoint = 2,
    ack_alexa_thermostat_controller_set_target_temperature_payload_object_member_upper_setpoint = 3,
    ack_alexa_thermostat_controller_set_target_temperature_payload_object_member_schedule = 4
}
ack_alexa_thermostat_controller_set_target_temperature_payload_object_member;

typedef enum _ack_alexa_thermostat_controller_adaptive_recovery_status
{
    ack_alexa_thermostat_controller_adaptive_recovery_status_preheating = 1,
    ack_alexa_thermostat_controller_adaptive_recovery_status_precooling = 2,
    ack_alexa_thermostat_controller_adaptive_recovery_status_inactive = 3
}
ack_alexa_thermostat_controller_adaptive_recovery_status;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ALEXA_THERMOSTAT_CONTROLLER_H__
