// This code was generated by a tool on Thu, 15 Apr 2021 06:17:29 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Alexa.DeviceUsage.Meter'.

#ifndef __ACK_GENERATED_ALEXA_DEVICE_USAGE_METER_H__
#define __ACK_GENERATED_ALEXA_DEVICE_USAGE_METER_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_alexa_device_usage_meter_reduce_resolution_payload_object_member
{
    ack_alexa_device_usage_meter_reduce_resolution_payload_object_member_limit = 1,
    ack_alexa_device_usage_meter_reduce_resolution_payload_object_member_duration = 2
}
ack_alexa_device_usage_meter_reduce_resolution_payload_object_member;

typedef enum _ack_alexa_device_usage_meter_directive_name
{
    ack_alexa_device_usage_meter_directive_name_report_measurements = 1,
    ack_alexa_device_usage_meter_directive_name_reduce_resolution = 2,
    ack_alexa_device_usage_meter_directive_name_invalid_measurement_error = 3
}
ack_alexa_device_usage_meter_directive_name;

typedef enum _ack_alexa_device_usage_meter_invalid_measurement_error_code
{
    ack_alexa_device_usage_meter_invalid_measurement_error_code_in_future = 1,
    ack_alexa_device_usage_meter_invalid_measurement_error_code_negative_value = 2,
    ack_alexa_device_usage_meter_invalid_measurement_error_code_invalid_meter_reset = 3,
    ack_alexa_device_usage_meter_invalid_measurement_error_code_interval_overlap = 4,
    ack_alexa_device_usage_meter_invalid_measurement_error_code_invalid_interval_start_end = 5
}
ack_alexa_device_usage_meter_invalid_measurement_error_code;

typedef enum _ack_alexa_device_usage_meter_measurements_report_event_payload_object_member
{
    ack_alexa_device_usage_meter_measurements_report_event_payload_object_member_electricity_intervals = 1,
    ack_alexa_device_usage_meter_measurements_report_event_payload_object_member_natural_gas_intervals = 2
}
ack_alexa_device_usage_meter_measurements_report_event_payload_object_member;

typedef enum _ack_alexa_device_usage_meter_event_name
{
    ack_alexa_device_usage_meter_event_name_measurements_report = 1
}
ack_alexa_device_usage_meter_event_name;

typedef enum _ack_alexa_device_usage_meter_invalid_measurement_error_payload_object_member
{
    ack_alexa_device_usage_meter_invalid_measurement_error_payload_object_member_electricity = 1,
    ack_alexa_device_usage_meter_invalid_measurement_error_payload_object_member_natural_gas = 2
}
ack_alexa_device_usage_meter_invalid_measurement_error_payload_object_member;

typedef enum _ack_alexa_device_usage_meter_interval_object_member
{
    ack_alexa_device_usage_meter_interval_object_member_usage = 1,
    ack_alexa_device_usage_meter_interval_object_member_start = 2,
    ack_alexa_device_usage_meter_interval_object_member_end = 3
}
ack_alexa_device_usage_meter_interval_object_member;

typedef enum _ack_alexa_device_usage_meter_invalid_measurement_error_object_member
{
    ack_alexa_device_usage_meter_invalid_measurement_error_object_member_error_code = 1,
    ack_alexa_device_usage_meter_invalid_measurement_error_object_member_time_of_error = 2
}
ack_alexa_device_usage_meter_invalid_measurement_error_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ALEXA_DEVICE_USAGE_METER_H__
