// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'EnumeratedPowerLevel'.

#ifndef __ACK_GENERATED_ENUMERATED_POWER_LEVEL_H__
#define __ACK_GENERATED_ENUMERATED_POWER_LEVEL_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_enumerated_power_level_object_member
{
    ack_enumerated_power_level_object_member_value = 1
}
ack_enumerated_power_level_object_member;

typedef enum _ack_enumerated_power_level
{
    ack_enumerated_power_level_low = 1,
    ack_enumerated_power_level_med_low = 2,
    ack_enumerated_power_level_medium = 3,
    ack_enumerated_power_level_med_high = 4,
    ack_enumerated_power_level_high = 5
}
ack_enumerated_power_level;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ENUMERATED_POWER_LEVEL_H__
