// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'InventoryCount'.

#ifndef __ACK_GENERATED_INVENTORY_COUNT_H__
#define __ACK_GENERATED_INVENTORY_COUNT_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_inventory_count_object_member
{
    ack_inventory_count_object_member_value = 1
}
ack_inventory_count_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_INVENTORY_COUNT_H__
