// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Alexa.ToggleController'.

#ifndef __ACK_GENERATED_ALEXA_TOGGLE_CONTROLLER_H__
#define __ACK_GENERATED_ALEXA_TOGGLE_CONTROLLER_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_alexa_toggle_controller_property_name
{
    ack_alexa_toggle_controller_property_name_toggle_state = 1
}
ack_alexa_toggle_controller_property_name;

typedef enum _ack_alexa_toggle_controller_directive_name
{
    ack_alexa_toggle_controller_directive_name_turn_on = 1,
    ack_alexa_toggle_controller_directive_name_turn_off = 2
}
ack_alexa_toggle_controller_directive_name;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ALEXA_TOGGLE_CONTROLLER_H__
