// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'ToggleState'.

#ifndef __ACK_GENERATED_TOGGLE_STATE_H__
#define __ACK_GENERATED_TOGGLE_STATE_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_toggle_state
{
    ack_toggle_state_on = 1,
    ack_toggle_state_off = 2
}
ack_toggle_state;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_TOGGLE_STATE_H__
