// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Alexa'.

#ifndef __ACK_GENERATED_ALEXA_H__
#define __ACK_GENERATED_ALEXA_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_alexa_change_report_payload_object_member
{
    ack_alexa_change_report_payload_object_member_change = 1
}
ack_alexa_change_report_payload_object_member;

typedef enum _ack_alexa_directive_name
{
    ack_alexa_directive_name_report_state = 1
}
ack_alexa_directive_name;

typedef enum _ack_alexa_device_mode
{
    ack_alexa_device_mode_color = 1,
    ack_alexa_device_mode_asleep = 2,
    ack_alexa_device_mode_not_provisioned = 3,
    ack_alexa_device_mode_other = 4
}
ack_alexa_device_mode;

typedef enum _ack_alexa_value_out_of_range_error_object_member
{
    ack_alexa_value_out_of_range_error_object_member_minimum_value = 1,
    ack_alexa_value_out_of_range_error_object_member_maximum_value = 2
}
ack_alexa_value_out_of_range_error_object_member;

typedef enum _ack_alexa_change_report_cause_type
{
    ack_alexa_change_report_cause_type_app_interaction = 1,
    ack_alexa_change_report_cause_type_physical_interaction = 2,
    ack_alexa_change_report_cause_type_periodic_poll = 3,
    ack_alexa_change_report_cause_type_rule_trigger = 4,
    ack_alexa_change_report_cause_type_voice_interaction = 5
}
ack_alexa_change_report_cause_type;

typedef enum _ack_alexa_event_name
{
    ack_alexa_event_name_response = 1,
    ack_alexa_event_name_error_response = 2,
    ack_alexa_event_name_state_report = 3,
    ack_alexa_event_name_change_report = 4
}
ack_alexa_event_name;

typedef enum _ack_alexa_change_report_change_object_member
{
    ack_alexa_change_report_change_object_member_cause = 1,
    ack_alexa_change_report_change_object_member_properties = 2
}
ack_alexa_change_report_change_object_member;

typedef enum _ack_alexa_error_type
{
    ack_alexa_error_type_invalid_value = 1,
    ack_alexa_error_type_value_out_of_range = 2,
    ack_alexa_error_type_temperature_value_out_of_range = 3,
    ack_alexa_error_type_endpoint_unreachable = 4,
    ack_alexa_error_type_no_such_endpoint = 5,
    ack_alexa_error_type_invalid_directive = 6,
    ack_alexa_error_type_internal_error = 7,
    ack_alexa_error_type_firmware_out_of_date = 8,
    ack_alexa_error_type_hardware_malfunction = 9,
    ack_alexa_error_type_rate_limit_exceeded = 10,
    ack_alexa_error_type_invalid_authorization_credential = 11,
    ack_alexa_error_type_expired_authorization_credential = 12,
    ack_alexa_error_type_not_supported_in_current_mode = 13,
    ack_alexa_error_type_already_in_operation = 14,
    ack_alexa_error_type_bridge_unreachable = 15,
    ack_alexa_error_type_endpoint_busy = 16,
    ack_alexa_error_type_endpoint_low_power = 17,
    ack_alexa_error_type_not_in_operation = 18,
    ack_alexa_error_type_power_level_not_supported = 19
}
ack_alexa_error_type;

typedef enum _ack_alexa_temperature_value_out_of_range_object_member
{
    ack_alexa_temperature_value_out_of_range_object_member_minimum_value = 1,
    ack_alexa_temperature_value_out_of_range_object_member_maximum_value = 2
}
ack_alexa_temperature_value_out_of_range_object_member;

typedef enum _ack_alexa_change_report_cause_object_member
{
    ack_alexa_change_report_cause_object_member_type = 1
}
ack_alexa_change_report_cause_object_member;

typedef enum _ack_alexa_error_response_payload_object_member
{
    ack_alexa_error_response_payload_object_member_type = 1,
    ack_alexa_error_response_payload_object_member_message = 2,
    ack_alexa_error_response_payload_object_member_value_out_of_range_valid_range = 3,
    ack_alexa_error_response_payload_object_member_not_supported_in_current_mode_current_device_mode = 3,
    ack_alexa_error_response_payload_object_member_temperature_value_out_of_range_valid_range = 3
}
ack_alexa_error_response_payload_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ALEXA_H__
