// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Alexa.Cooking.TimeController'.

#ifndef __ACK_GENERATED_ALEXA_COOKING_TIME_CONTROLLER_H__
#define __ACK_GENERATED_ALEXA_COOKING_TIME_CONTROLLER_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_alexa_cooking_time_controller_property_name
{
    ack_alexa_cooking_time_controller_property_name_requested_cook_time = 1,
    ack_alexa_cooking_time_controller_property_name_cooking_power_level = 2
}
ack_alexa_cooking_time_controller_property_name;

typedef enum _ack_alexa_cooking_time_controller_cook_by_time_payload_object_member
{
    ack_alexa_cooking_time_controller_cook_by_time_payload_object_member_cook_time = 1,
    ack_alexa_cooking_time_controller_cook_by_time_payload_object_member_cooking_mode = 2,
    ack_alexa_cooking_time_controller_cook_by_time_payload_object_member_food_item = 3,
    ack_alexa_cooking_time_controller_cook_by_time_payload_object_member_cooking_power_level = 4,
    ack_alexa_cooking_time_controller_cook_by_time_payload_object_member_target_cooking_temperature = 5
}
ack_alexa_cooking_time_controller_cook_by_time_payload_object_member;

typedef enum _ack_alexa_cooking_time_controller_directive_name
{
    ack_alexa_cooking_time_controller_directive_name_cook_by_time = 1,
    ack_alexa_cooking_time_controller_directive_name_adjust_cook_time = 2
}
ack_alexa_cooking_time_controller_directive_name;

typedef enum _ack_alexa_cooking_time_controller_adjust_cook_time_payload_object_member
{
    ack_alexa_cooking_time_controller_adjust_cook_time_payload_object_member_cook_time_delta = 1
}
ack_alexa_cooking_time_controller_adjust_cook_time_payload_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ALEXA_COOKING_TIME_CONTROLLER_H__
