// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'Connectivity'.

#ifndef __ACK_GENERATED_CONNECTIVITY_H__
#define __ACK_GENERATED_CONNECTIVITY_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_connectivity
{
    ack_connectivity_unreachable = 1,
    ack_connectivity_ok = 2
}
ack_connectivity;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_CONNECTIVITY_H__
