// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'ItemQuantity'.

#ifndef __ACK_GENERATED_ITEM_QUANTITY_H__
#define __ACK_GENERATED_ITEM_QUANTITY_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_item_quantity_object_type
{
    ack_item_quantity_object_type_weight = 1,
    ack_item_quantity_object_type_volume = 2,
    ack_item_quantity_object_type_count = 3
}
ack_item_quantity_object_type;

typedef enum _ack_item_quantity_object_member
{
    ack_item_quantity_object_member_type = 1,
    ack_item_quantity_object_member_value = 2
}
ack_item_quantity_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_ITEM_QUANTITY_H__
