// This code was generated by a tool on Wed, 3 Jun 2020 22:07:10 GMT.
// DO NOT EDIT MANUALLY.

// Instruction artifact: 'RequiredInteraction'.

#ifndef __ACK_GENERATED_REQUIRED_INTERACTION_H__
#define __ACK_GENERATED_REQUIRED_INTERACTION_H__

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum _ack_required_interaction
{
    ack_required_interaction_none = 0,
    ack_required_interaction_baste = 1,
    ack_required_interaction_check = 2,
    ack_required_interaction_cover = 3,
    ack_required_interaction_peel_back_film = 4,
    ack_required_interaction_poke = 5,
    ack_required_interaction_replace_film = 6,
    ack_required_interaction_rotate = 7,
    ack_required_interaction_stir = 8,
    ack_required_interaction_toss = 9,
    ack_required_interaction_turn_over = 10,
    ack_required_interaction_uncover = 11,
    ack_required_interaction_custom = 12
}
ack_required_interaction;

typedef enum _ack_required_interaction_object_member
{
    ack_required_interaction_object_member_value = 1
}
ack_required_interaction_object_member;

#ifdef __cplusplus
}
#endif

#endif // ndef __ACK_GENERATED_REQUIRED_INTERACTION_H__
